name = "tmi"
type = "javascript"
account_id = "4e8dfcfd8f2ba73417df49c9c7956c6f"
workers_dev = true
route = "tmi.piero-simplistic.workers.dev"
zone_id = ""

[site]
bucket = "dist/client"
entry-point = "."

[build]
upload.format = "service-worker"
command = "yarn && yarn build"