// This is autogenerated by running
// npm run tw:dump-screens
const Screens = {
    
        'sm': {
            value: 640,
            size: '640px',
            mediaQuery: '(min-width: 640px)'
        }
    ,
        'md': {
            value: 768,
            size: '768px',
            mediaQuery: '(min-width: 768px)'
        }
    ,
        'lg': {
            value: 1024,
            size: '1024px',
            mediaQuery: '(min-width: 1024px)'
        }
    ,
        'xl': {
            value: 1280,
            size: '1280px',
            mediaQuery: '(min-width: 1280px)'
        }
    ,
        '2xl': {
            value: 1536,
            size: '1536px',
            mediaQuery: '(min-width: 1536px)'
        }
    ,
        '3xl': {
            value: 1650,
            size: '1650px',
            mediaQuery: '(min-width: 1650px)'
        }
    
}
export default Screens;